# Generated by Django 5.2.5 on 2026-09-04 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, default='', max_length=100)),
                ('estado_envio', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('emitida_en', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deudas', to='clientes.cliente')),
            ],
            options={
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_operacion_mc4', models.CharField(blank=True, default='', max_length=100)),
                ('monto_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('pendiente_confirmacion', 'Pendiente de confirmación'), ('pagado', 'Pagado'), ('vencido', 'Vencido'), ('error', 'Error'), ('cancelado', 'Cancelado')], default='generado', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_qr', to='cobranza.deuda')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
