# Generated by Django 5.2.5 on 2026-09-04 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cobranza', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionqr',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_qr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='factura',
            name='transaccion_qr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='cobranza.transaccionqr'),
        ),
    ]
