# Generated by Django 5.2.5 on 2026-09-07 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0003_caja_aperturacajafueradehorario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='transaccion_qr',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='cobranza.transaccionqr'),
        ),
        migrations.CreateModel(
            name='CobroEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_recibido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vuelto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('caja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros_efectivo', to='cobranza.caja')),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros_efectivo', to='cobranza.deuda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobros_efectivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='cobro_efectivo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factura', to='cobranza.cobroefectivo'),
        ),
        migrations.AddConstraint(
            model_name='factura',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cobro_efectivo__isnull', True), ('transaccion_qr__isnull', False)), models.Q(('cobro_efectivo__isnull', False), ('transaccion_qr__isnull', True)), _connector='OR'), name='factura_tiene_exactamente_un_origen'),
        ),
    ]
