# Generated by Django 5.2.5 on 2026-09-07 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0004_alter_factura_transaccion_qr_cobroefectivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionqr',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_qr', to='cobranza.caja'),
        ),
    ]
