# Generated by Django 5.2.5 on 2026-09-09 13:05

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranza', '0005_transaccionqr_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='deuda',
            name='items_snapshot',
            field=models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='factura',
            name='cobranzas_uuid',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='factura',
            name='comprobante_pdf',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='factura',
            name='intentos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
