# Generated by Django 5.2.5 on 2026-09-04 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_externo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('nit_ci', models.CharField(blank=True, default='', max_length=30)),
            ],
        ),
    ]
