# Generated by Django 5.2.5 on 2026-09-09 00:46

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100, unique=True)),
                ('origen', models.CharField(choices=[('cessa_laravel_web', 'cessa-laravel (pago QR web)')], default='cessa_laravel_web', max_length=30)),
                ('nro_cliente', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='BOB', max_length=3)),
                ('detalle', models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('fecha_pago', models.DateTimeField()),
                ('numero_orden_originante', models.CharField(blank=True, default='', max_length=50)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('facturado', 'Facturado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('cobranzas_uuid', models.CharField(blank=True, default='', max_length=100)),
                ('comprobante_pdf', models.BinaryField(blank=True, null=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('recibido_en', models.DateTimeField(auto_now_add=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-recibido_en'],
            },
        ),
    ]
