# Generated by Django 5.2.5 on 2026-10-06 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion_externa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudliquidacion',
            name='banco',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
